export const ADD_PROVIDER = 'provider/ADD_PROVIDER';
export const GET_PROVIDER = 'provider/GET_PROVIDER';
export const SET_PROVIDER = 'provider/SET_PROVIDER';
export const GET_LIST_PROVIDER = 'PROVIDER/GET_LIST_PROVIDER';
export const SET_LIST_PROVIDER = 'PROVIDER/SET_LIST_PROVIDER';
export const EDIT_PROVIDER = 'provider/EDIT_PROVIDER';
export const DELETE_PROVIDER = 'provider/DELETE_PROVIDER';

export default {
	ADD_PROVIDER,
	GET_PROVIDER,
	SET_PROVIDER,
	GET_LIST_PROVIDER,
	SET_LIST_PROVIDER,
	EDIT_PROVIDER,
	DELETE_PROVIDER,
};
